@startuml BirdStateMachine
state "BirdStateMachine State" as FlappyBirdGame_Game_Creature_BirdStateMachine_State {
  state "Alive" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive {
    state "Fall" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Fall
    state "Flap" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Flap
  }
  state "Dead" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Dead
  state "Wait" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Wait
}

FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Dead : Collide
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Fall --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Flap : Flap
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Flap --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Fall : Fall
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Dead --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Wait : Flap
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Wait --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Flap : Flap

FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Fall : OnEnter → RotationChange
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Fall : Run() → FallDown
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Flap : OnEnter → RotationChange
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Alive_Flap : Run() → FlyUp
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Dead : OnFlap → Reset

[*] --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Wait
@enduml