@startuml BirdStateMachine
state "BirdStateMachine State" as FlappyBirdGame_Game_Creature_BirdStateMachine_State {
  state "Dead" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Dead
  state "Fly" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly {
    state "Fall" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly_Fall
    state "Flap" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly_Flap
  }
  state "Wait" as FlappyBirdGame_Game_Creature_BirdStateMachine_State_Wait
}

FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Dead : Collide
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly_Fall --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly_Flap : Flap
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly_Flap --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly_Fall : Fall
FlappyBirdGame_Game_Creature_BirdStateMachine_State_Wait --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Fly_Flap : Flap
[*] --> FlappyBirdGame_Game_Creature_BirdStateMachine_State_Wait
@enduml